name: AO_buoy_predict
channels:
  - defaults
  - conda-forge
dependencies:
  - seaborn
  - joblib
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - xarray
  - netCDF4
  - dask
  - scipy
  - requests
  - beautifulsoup4
  - statsmodels
  - pip
  - geopandas 
  - shapely 
  - pyproj  
  - rasterio 
  - folium  
  - plotly
  - tqdm
  - cdsapi
  - ipython
  - glob2
  - geopy
  - xgboost
  - lightgbm
  - cartopy
  - pip:
      - tensorflow
      - keras
      - h5py
      - jupyter-dash
      - datetime
      - pykalman
      - scipy
      - haversine
      - optuna